import type { EquippedItem, NormalizedCharacterProfile } from "@/domain/character";

function isoHoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

function isoDaysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

function mockItem(slot: string, name: string, options: Array<[string, string]> = []): EquippedItem {
  return {
    slot,
    part: slot,
    name,
    iconUrl: null,
    shapeName: null,
    shapeIconUrl: null,
    description: null,
    starforce: "22",
    scrollUpgrade: "12",
    potentialGrade: "레전드리",
    potentialOptions: ["STR : +12%", "STR : +9%", "공격력 : +12%"],
    additionalPotentialGrade: "유니크",
    additionalPotentialOptions: ["STR : +6%", "공격력 : +10"],
    totalOptions: options.map(([label, value]) => ({ label, value })),
    baseOptions: [],
    addOptions: [],
    exceptionalOptions: [],
    etcOptions: [],
    soulName: null,
    soulOption: null,
  };
}

const starlightEquipment = [
  mockItem("무기", "데모 양손검", [
    ["공격력", "+398"],
    ["보스 몬스터 데미지", "+30%"],
  ]),
  mockItem("모자", "데모 전사 모자", [["STR", "+136"]]),
  mockItem("상의", "데모 전사 상의", [["STR", "+112"]]),
  mockItem("하의", "데모 전사 하의", [["STR", "+112"]]),
  mockItem("장갑", "데모 전사 장갑", [["크리티컬 데미지", "+8%"]]),
  mockItem("신발", "데모 전사 신발", [["STR", "+108"]]),
  mockItem("망토", "데모 전사 망토", [["공격력", "+30"]]),
  mockItem("보조무기", "데모 보조무기", [["방어율 무시", "+40%"]]),
];

export function getMockProfiles(): NormalizedCharacterProfile[] {
  return [
    {
      ocid: "mock-starlight-knight",
      characterName: "별빛검사",
      worldName: "루나",
      className: "히어로",
      level: 286,
      imageUrl: null,
      currentGuild: "별의항해",
      fetchedAt: isoHoursAgo(2),
      sourceDate: new Date().toISOString().slice(0, 10),
      provider: "mock",
      fields: [
        {
          key: "combatPower",
          label: "전투력",
          value: "178,420,000",
          provenance: "NEXON_API",
          category: "combat",
          priorityByRole: { DAMAGE: 1, SUPPORT: 5 },
        },
        {
          key: "union",
          label: "유니온",
          value: "9,150",
          provenance: "NEXON_API",
          category: "growth",
          priorityByRole: { DAMAGE: 3, SUPPORT: 3, UTILITY: 3, OTHER: 4 },
        },
        {
          key: "hexa",
          label: "HEXA",
          value: "6차 28레벨",
          provenance: "NEXON_API",
          category: "growth",
          priorityByRole: { DAMAGE: 4, SUPPORT: 5, UTILITY: 5, OTHER: 5 },
        },
        {
          key: "equipment",
          label: "장비 요약",
          value: "앱솔랩스·아케인 혼합",
          provenance: "NEXON_API",
          category: "equipment",
          priorityByRole: { DAMAGE: 5, SUPPORT: 6, UTILITY: 6, OTHER: 6 },
        },
      ],
      stats: [
        { label: "전투력", value: "178,420,000" },
        { label: "보스 몬스터 데미지", value: "412%" },
        { label: "방어율 무시", value: "95.12%" },
        { label: "크리티컬 데미지", value: "98.0%" },
      ],
      equipmentPresetNo: 1,
      equipment: starlightEquipment,
      symbols: [
        {
          name: "데모 아케인 심볼",
          iconUrl: null,
          level: "20",
          force: "13200",
          stats: [{ label: "STR", value: "+13200" }],
        },
      ],
      cashEquipment: [],
      setEffects: [],
      rawAvailability: {
        basic: "available",
        stat: "available",
        equipment: "available",
        hexa: "available",
        union: "available",
        symbol: "available",
        cashEquipment: "available",
        setEffect: "available",
        guild: "available",
      },
      notice: "현재 데모 데이터로 표시 중입니다.",
    },
    {
      ocid: "mock-luna-healer",
      characterName: "루나힐러",
      worldName: "크로아",
      className: "비숍",
      level: 283,
      imageUrl: null,
      currentGuild: "달빛연합",
      fetchedAt: isoHoursAgo(4),
      sourceDate: new Date().toISOString().slice(0, 10),
      provider: "mock",
      fields: [
        {
          key: "combatPower",
          label: "전투력",
          value: "82,160,000",
          provenance: "NEXON_API",
          category: "combat",
          priorityByRole: { DAMAGE: 2, SUPPORT: 1, UTILITY: 2, OTHER: 2 },
        },
        {
          key: "union",
          label: "유니온",
          value: "8,950",
          provenance: "NEXON_API",
          category: "growth",
          priorityByRole: { DAMAGE: 4, SUPPORT: 1, UTILITY: 2, OTHER: 4 },
        },
        {
          key: "hexa",
          label: "HEXA",
          value: "6차 24레벨",
          provenance: "NEXON_API",
          category: "growth",
          priorityByRole: { DAMAGE: 5, SUPPORT: 2, UTILITY: 3, OTHER: 5 },
        },
        {
          key: "supportSetup",
          label: "지원 세팅",
          value: "보스 지원 중심",
          provenance: "NEXON_API",
          category: "combat",
          priorityByRole: { SUPPORT: 3, UTILITY: 1 },
        },
      ],
      stats: [
        { label: "전투력", value: "82,160,000" },
        { label: "보스 몬스터 데미지", value: "278%" },
        { label: "방어율 무시", value: "92.34%" },
      ],
      equipmentPresetNo: 2,
      equipment: [
        mockItem("무기", "데모 스태프", [["마력", "+392"]]),
        mockItem("모자", "데모 마법사 모자", [["INT", "+136"]]),
        mockItem("장갑", "데모 마법사 장갑", [["크리티컬 데미지", "+8%"]]),
      ],
      symbols: [],
      cashEquipment: [],
      setEffects: [],
      rawAvailability: {
        basic: "available",
        stat: "available",
        equipment: "available",
        hexa: "available",
        union: "available",
        symbol: "missing",
        cashEquipment: "missing",
        setEffect: "missing",
        guild: "available",
      },
      notice: "일부 정보는 불러오지 못했지만 기본 정보로 계속 작성할 수 있습니다.",
    },
    {
      ocid: "mock-old-adventurer",
      characterName: "오래된모험가",
      worldName: "스카니아",
      className: "아크메이지(불,독)",
      level: 278,
      imageUrl: null,
      currentGuild: null,
      fetchedAt: isoHoursAgo(30),
      sourceDate: isoDaysAgo(2).slice(0, 10),
      provider: "mock",
      fields: [
        {
          key: "union",
          label: "유니온",
          value: "8,720",
          provenance: "NEXON_API",
          category: "growth",
          priorityByRole: { DAMAGE: 2, SUPPORT: 2, UTILITY: 2, OTHER: 2 },
        },
        {
          key: "hexa",
          label: "HEXA",
          value: "6차 19레벨",
          provenance: "NEXON_API",
          category: "growth",
          priorityByRole: { DAMAGE: 1, SUPPORT: 2, UTILITY: 2, OTHER: 2 },
        },
      ],
      stats: [{ label: "전투력", value: "41,200,000" }],
      equipmentPresetNo: null,
      equipment: [],
      symbols: [],
      cashEquipment: [],
      setEffects: [],
      rawAvailability: {
        basic: "available",
        stat: "available",
        equipment: "missing",
        hexa: "available",
        union: "available",
        symbol: "missing",
        cashEquipment: "missing",
        setEffect: "missing",
        guild: "missing",
      },
      notice: "현재 데모 데이터로 표시 중입니다.",
    },
  ];
}
